### ISSUE TITLE
Bug 3104: SEGV in TSnapShotContainer::mergeChildren with Oracle JDK8u92

### ISSUE THREAD

**Issue by ykubota** [HeapStats/heapstats#31]
We got crash report from wyukawa via twitter. Thanks wyukawa :)

Available info. 
hs_err log: https://gist.github.com/wyukawa/f41b1619447edff2aa78b237bd5b3dfa
Backtrace log of coredump: https://gist.github.com/wyukawa/a5facaba88b7d7159314858d3d6690fb

hs_err says that SEGV occurred in TSnapShotContainer::mergeChildren.

**Comment by wyukawa** [comment]
Today, I encountered second presto worker crash...
So now I don't recommend to use presto with heapstats.
I hope that heapstats is fixed.

presto jvm.config is the following

```
-server
-Xmx16G
-XX:+UseG1GC
-XX:+UseGCOverheadLimit
-XX:+ExplicitGCInvokesConcurrent
-XX:+HeapDumpOnOutOfMemoryError
-XX:OnOutOfMemoryError=kill -9 %p
-agentlib:heapstats
```

Thanks

**Comment by YaSuenag** [comment]
@wyukawa Can you share hs_err log?

**Comment by wyukawa** [comment]
Sure

https://gist.github.com/wyukawa/03b973aecd9740d036690888d838b67d

**Comment by YaSuenag** [comment]
I guess this crash will be occurred after class unloading.
If HotSpot unloades class(es), HeapStats agent hooks it through ClassUnload JVMTI event and set `isRemoved` flag to `objData` (`TObjectData`) for unloaded class.
However, pointer to `objData` has `TChildClassCounter`. `TClassContainer::commitClassChange()` releases memory for `objData`. But this function does NOT treat references in `TChildClassCounter`.

Thus I guess this hs_err shows unmapped address which is caused of SEGV.
I think we have NOT to copy `objData` which has `isRemoved` flag for child data.

I checked SEGV address and memory mapping in two hs_err log.
They are near of top (native) heap address.
I guess these memory region were mapped in early timing, and they were unmapped which was caused by Metaspace GC.

**Comment by YaSuenag** [comment]
Oh, we have to skip child data which has removed `objData`. I've fixed it in [this commit](https://github.com/HeapStats/heapstats/commit/77ce3fd90fc8ea3050a1f808b25ee7d6002a6f0a).

**Comment by ykubota** [comment]
Both SEGV addresses , i.e., "wrong" `objData`, are nearly top of native heap address, so I also guess the classes of `objData` were unloaded.

Thanks YaSuenag for good catching and patches. 
Looks good to me. Please rebase and push it. 

Maybe we should add a new testcase as other issue if possible.

**Comment by YaSuenag** [comment]
@ykubota Sorry, my patch will occur memory leak.
I've fixed it. Could you review again?

**Comment by ykubota** [comment]
Oops.., sorry for wrong review. Please wait me to review.

**Comment by ykubota** [comment]
OK, looks good to me. Please rebase & push it :)
